### ISSUE TITLE
suddenly stops downloading more episodes

### ISSUE THREAD

**Issue by vicentehenrique1998** [Tenpi/Crunchyroll-Downloader#10]
i was downloading only the subtitles from https://www.crunchyroll.com/sengoku-collection-parallel-world-samurai and stopped downloading in episode 9, I tried to download again and stopped in the same episode.

**Comment by Tenpi** [comment]
Thanks for the bug report, this should be fixed in `v0.2.1`.

**Comment by vicentehenrique1998** [comment]
Thanks
