### ISSUE TITLE
Cannot download Dub version

### ISSUE THREAD

**Issue by MLB-11** [Tenpi/Crunchyroll-Downloader#101]
i cannot download all episodes of an anime with dub, i have to download one episode at once, i tried the name of the anime, the url, none of these worked
Thanks for this software <3.
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/98657556/c2fdb680-f453-4538-a01b-7775c8961e71)

**Comment by San3-Cod3** [comment]
Are you still able to download all of the episodes when downloading individually?

I ask this because sometimes on CR a Series is listed as having a DUB, and maybe some episodes are in DUBBED in English for example, or the DUB language you're looking for, and then the rest of the remaining episodes could be dubbed in say, Arabic, so when you try and grab it all in English it will error, or only the English ones would download - if that makes sense, and CR will NOT clarify about the DUB they have; they just say DUB... Which is annoying...

But of course something else could be happening but your explanation wasn't fully definitive.

Anyway, Tenpi will be the one to help you with this.

**Comment by MLB-11** [comment]
ok i see
hm, yes I can download the episodes individually it's just when I put the link of the anime directly the error comes.
Thank you for the quick reply !

**Comment by San3-Cod3** [comment]
> ok i see hm, yes I can download the episodes individually it's just when I put the link of the anime directly the error comes. Thank you for the quick reply !

Are you able to download the Series you need using the built-in web browser though?

Is it just links? As using the browser could be a solution potentially.

**Comment by MLB-11** [comment]
No, with the built-in browser this doesn't work either

> > ok i see hm, yes I can download the episodes individually it's just when I put the link of the anime directly the error comes. Thank you for the quick reply !
> 
> Are you able to download the Series you need using the built-in web browser though?
> 
> Is it just links causing errors? As using the browser could be a solution potentially.

**Comment by San3-Cod3** [comment]
Are you able to download Blue Lock episode 4 in the language you want?

**Comment by MLB-11** [comment]
yes
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/98657556/1be3d570-3552-4c89-a02c-264699309865)

**Comment by San3-Cod3** [comment]
Is it only the original Japanese audio you're trying to download?

If so, the reason could be because you are using "Type: dub", when for Japanese you should be using "Type: sub", as Japanese is not a DUB, it is the original language in which you watched with SUBS/SUBTITLES.

**Comment by MLB-11** [comment]
actually, first I download in dub (japanese mp4) and then I download the subtitles (french .ass / english .ass) because I want them externally.

**Comment by San3-Cod3** [comment]
> actually, first I download in dub (japanese mp4) and then I download the subtitles (french .ass / english .ass) because I want them externally.

What I'm saying to you is: Japanese is NOT a DUB - you may just need to reset your setting and choose "Type: sub", and then choose "Language: French".

Which will give you: Japanese original audio with French subtitles.

**Comment by MLB-11** [comment]
hm yes i understand, I thought that dub was just the audio/video and sub audio/video + subtitles, but suddenly how do I download just the audio/video in Japanese and the French subtitles but not included on the video ?

**Comment by San3-Cod3** [comment]
> hm yes i understand, I thought that dub was just the audio/video and sub audio/video + subtitles, but suddenly how do I download just the audio/video in Japanese and the French subtitles but not included on the video ?

When you download in Japanese, which is "Type: sub" and "Language: *", you will always get the subtitles with it as this is normal behaviour when downloading what is known as SUB, Japanese original audio with your chosen languages subtitles - now, if you want external subtitles by themselves, do the following: "Format: ass / vtt" -- this will not download any file with video or audio, but instead will give you an external subtitle file in either *.ASS or *.VTT like you asked.

**Comment by San3-Cod3** [comment]
I will suggest an idea to @Tenpi I have that could clear up some confusion like certain things discussed here.  I will edit this comment with my idea further below at some point.

**Comment by Tenpi** [comment]
download as mkv or mp4 with "no re-encoding" codec to use soft subtitles.

**Comment by MLB-11** [comment]
oh okay, thanks guys i'm trying it

**Comment by MLB-11** [comment]
> download as mkv or mp4 with "no re-encoding" codec to use soft subtitles.

ok thanks it work fine <3
