### ISSUE TITLE
Impossible to download

### ISSUE THREAD

**Issue by Pipixel** [Tenpi/Crunchyroll-Downloader#11]
I don't know why but I can't download videos, even after reinstalling the software with Revo Uninstaller nothing changes, log into my account too or install FFMPEG on my computer

**Comment by Tenpi** [comment]
Have you checked that the subtitle/dub language is available on crunchyroll? Otherwise, please provide the error messages. Open the developer tools with `Ctrl+Shift+I` go to the console tab.

You don't have to install ffmpeg, it comes bundled with it.

**Comment by Pipixel** [comment]
> Have you checked that the subtitle/dub language is available on crunchyroll? Otherwise, please provide the error messages. Open the developer tools with `Ctrl+Shift+I` go to the console tab.
> 
> You don't have to install ffmpeg, it comes bundled with it.

The sub and dub are right, this is what I have after opening the console
[https://i.imgur.com/C0SsHGF.png](url)

**Comment by Tenpi** [comment]
> The sub and dub are right, this is what I have after opening the console
> https://i.imgur.com/C0SsHGF.png

I need to know what URL(s) you are entering, because I cannot reproduce this error.

**Comment by Pipixel** [comment]
Here the link : https://www.crunchyroll.com/fr/that-time-i-got-reincarnated-as-a-slime
It comes from all Crunchyroll on my side, and I don't explain it either

**Comment by Tenpi** [comment]
> Here the link : https://www.crunchyroll.com/fr/that-time-i-got-reincarnated-as-a-slime
> It comes from all Crunchyroll on my side, and I don't explain it either

Go to `C:\Users\[your name]\AppData\Roaming\crunchyroll-downloader` and delete the `config.json`. If the problem is an invalid cookie that should reset it.

**Comment by Pipixel** [comment]
It works now, thank you

**Comment by Tenpi** [comment]
> It works now, thank you

But I still wonder, how did you get an invalid cookie? Have you modified this file before? Or does the problem come back when you login again (in which case it's probably a bug with how I store it).

**Comment by Pipixel** [comment]
I don't know, I didn't touch the file or anything, the only time I got logged is when it didn't work

**Comment by Tenpi** [comment]
> I don't know, I didn't touch the file or anything, the only time I got logged is when it didn't work

Ok, reopen this issue if you have the same problem again.
