### ISSUE TITLE
[Request] Some options that might be useful in my point of view

### ISSUE THREAD

**Issue by Pipixel** [Tenpi/Crunchyroll-Downloader#12]
Here is a small list of additions for the next versions, if I have other ideas, I will propose them

- Launch the software in the download options already entered before closing
- Choose the maximum speed
- Organize the download queue according to the episode number, for example the first episode at the top of the list
- Choose a maximum number of episodes to download at the same time
- Choose to separate seasons into folders
- Have the possibility to download separately either only the dub or the sub
- Indicate that an account is connected and specify if it's premium or not and its nickname
- Add a button "delete cookies" and "recreate config.json" in case of problems
- Allow the possibility to add "skin" on the software
- Add a play button after downloading a video
- Choose the video encoding method for example: H.264 or H.265

**Comment by Tenpi** [comment]
> * Organize the download queue according to the episode number, for example the first episode at the top of the list
> * Add a button "delete cookies" and "recreate config.json" in case of problems
> * Add a play button after downloading a video

Yeah, sure. These are all good ideas.

> * Choose to separate seasons into folders

It's already possible, look at the options for the output template in the readme, for example you can set it to `{seasonTitle}/{episodeTitle} {episodeNumber}` (use slashes to indicate subfolders)

> * Have the possibility to download separately either only the dub or the sub

It's already possible, you can filter between dubs and subs by changing the "type".

> * Launch the software in the download options already entered before closing

Not sure I understand what this means.
> * Choose the maximum speed
> * Choose the video encoding method for example: H.264 or H.265

Not that necessary imo.
> * Choose a maximum number of episodes to download at the same time
> * Indicate that an account is connected and specify if it's premium or not and its nickname
> * Allow the possibility to add "skin" on the software

All of these are a lot more complicated to add, they aren't bad ideas but they're much harder to implement.

Thanks for your suggestions, I am pretty busy with school but I'll hopefully get around to adding some of them.

**Comment by Pipixel** [comment]
> > * Launch the software in the download options already entered before closing
> 
> Not sure I understand what this means.
> 
When the program is closed and reopened everything is reset to the default settings like language or format, I mean and sorry if this is not clearly explained is that the settings remain as they are before the program is closed

**Comment by Tenpi** [comment]
> > > * Launch the software in the download options already entered before closing
> > 
> > 
> > Not sure I understand what this means.
> 
> When the program is closed and reopened everything is reset to the default settings like language or format, I mean and sorry if this is not clearly explained is that the settings remain as they are before the program is closed

Upgrade to `v0.2.2`. It should now persist the settings between closes. I also added the play button and a button for deleting cookies.

**Comment by Pipixel** [comment]
I realized when I downloaded the update that there was no download window. Would it be possible to integrate one?

**Comment by Tenpi** [comment]
> I realized when I downloaded the update that there was no download window. Would it be possible to integrate one?

It's another feature that's pretty pointless imo. Unless you have poor internet the download should be almost instant

**Comment by ajipw** [comment]
is it possible to add us cookies option?

**Comment by Tenpi** [comment]
> is it possible to add US cookies option?

No, but you can use a proxy/vpn.

**Comment by Tenpi** [comment]
Implemented most of these
