### ISSUE TITLE
Bug link

### ISSUE THREAD

**Issue by Pipixel** [Tenpi/Crunchyroll-Downloader#13]
The episode links do not work on the latest version but work on the previous one, however for the whole series there is no problem:
https://www.crunchyroll.com/fr/jujutsu-kaisen/episode-23-the-origin-of-blind-obedience-2-801616 (example of link I used)

![Crunchyroll_Downloader_UJlz6ULRfH](https://user-images.githubusercontent.com/66361896/112568057-2d799480-8de2-11eb-8620-d71ec5a938c5.png)

**Comment by Pipixel** [comment]
Never mind, I just wasn't logged into my account

**Comment by Tenpi** [comment]
It downloads from the English site, so the premium episode previews can only be downloaded in English. The reason why is because of an earlier bug (#8), so if you want to download the previews in French I'm sorry.
