### ISSUE TITLE
Can't download multi episode (dub)

### ISSUE THREAD

**Issue by N3ars** [Tenpi/Crunchyroll-Downloader#14]
hi there, 
Seems like there is a bug when you try to download a whole season concerning the dub version, it downloads only the last episode with a bugged progressbar.

**Comment by Tenpi** [comment]
show name?

**Comment by N3ars** [comment]
It happens to every anime, but i tried on this one https://www.crunchyroll.com/dr-stone, i wanted to dl the VF version

**Comment by Tenpi** [comment]
Upgrade and download using the download button on the browser (not the search bar). Make sure that the episodes are loaded on the page. Simply put, not all the episodes exist when the page initially loads which I think is to speed up the loading time.

**Comment by N3ars** [comment]
Working like a charm, thank you! 
closing this issue.
