### ISSUE TITLE
Could please add support for beta.crunchyroll.com

### ISSUE THREAD

**Issue by malzen** [Tenpi/Crunchyroll-Downloader#17]
When I download a show does not work when this is beta.crunchyroll.com only works on crunchyroll.com

**Comment by Tenpi** [comment]
Well, yeah. Beta crunchyroll is basically a new website. Whenever the beta replaces regular crunchyroll I'll add support for it.

**Comment by hmm-norah** [comment]
[beta.crunchyroll.com is now required for US users, and the menu option to switch back is disabled.](https://www.crunchyroll.com/forumtopic-1024293/how-to-turn-back-to-the-normal-cr-player-and-not-the-beta-one#58819247)

I have no idea why they decided to do this, while also still referring to it as a 'beta'.

**Comment by Tenpi** [comment]
> [beta.crunchyroll.com is now required for US users, and the menu option to switch back is disabled.](https://www.crunchyroll.com/forumtopic-1024293/how-to-turn-back-to-the-normal-cr-player-and-not-the-beta-one#58819247)

Thanks for letting me know, I’ll work on adding support for the beta later.

**Comment by Tenpi** [comment]
Added support for the beta in `v0.2.4`. PNG downloads are not supported on the beta at this time (I just couldn't find them...)
