### ISSUE TITLE
Downloads getting stuck

### ISSUE THREAD

**Issue by RaulRohjans** [Tenpi/Crunchyroll-Downloader#19]
I noticed that when downloading a ton of episiodes, a lot of them end up getting stuck. Sometimes instead of completing, they go over 100%. Is there any way I can download one at a time?

**Comment by Tenpi** [comment]
You can download one at a time by providing the direct url to the episode. Due to the random nature of this bug it doesn't seem like something I can fix unfortunately.

**Comment by RaulRohjans** [comment]
Thank you for the reply. Providing one link at a time is really time consuming and prone to mistakes when there are a lot of episodes, and since this is a desktop app, I dont really see a way to automate downloads with a script.

This has probably been discussed already but maybe implementing a max simultaneous downloads setting should help with the problem.

**Comment by Tenpi** [comment]
> This has probably been discussed already but maybe implementing a max simultaneous downloads setting should help with the problem.

Adding a "queue" system would be fairly complex, and I don't think this bug is that huge of a problem to warrant it. However, I will leave it for future consideration.

**Comment by RaulRohjans** [comment]
I havent looked into the code yet, so I dont really know if this is possible. Lets assume the person chooses 2 max downloads in the settings. Then the person inserts the link and presses download. What you could do is start downloading all the episodes, pause all of them except for the first two and then as they complete, it unpauses the next one. 
If you had an array with all the episodes and the first one finished downloading, in order to know what episode to start next you could grab that episode's index and add the max downloads number (in this case 2), then, simply unpause the download for that video.

Sorry if this sounds a bit confusing or cant be done in this code, Im not really familiar with TypeScript, thats why I havent contributed to the app.

**Comment by Tenpi** [comment]
Added the queue system in `v0.2.5`. 

> Sorry if this sounds a bit confusing or cant be done in this code, Im not really familiar with TypeScript, thats why I havent contributed to the app.

Typescript is a great language, I recommend learning it! It's basically an extension to Javascript that fixes most of its problems (it adds typings, most notably).
