### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by malzen** [Tenpi/Crunchyroll-Downloader#2]
I have a issue when logging in it gives me a error "could not login".

**Comment by Tenpi** [comment]
Are you in the US? I'm not too sure if it works in other regions. If you forgot your password, you can follow their password reset process here: https://www.crunchyroll.com/resetpw

You get locked out for typing in the incorrect password multiple times, but I don't know for how long.

**Comment by malzen** [comment]
I typed everything correctly it's not logging in your application.

**Comment by Tenpi** [comment]
Ok, I will see if I find anything, but I'm too sure since I can login fine.

**Comment by Tenpi** [comment]
Hello, as of `v0.1.0` I replaced the login with a web browser, so you can login directly on the website. It uses your browser cookies to download instead. Let me know if there are any issues, I have not tested it a lot.

https://github.com/Tenpi/Crunchyroll-Downloader/releases

**Comment by malzen** [comment]
Works now login
