### ISSUE TITLE
Download finish, but duration still run

### ISSUE THREAD

**Issue by hippomu-media** [Tenpi/Crunchyroll-Downloader#23]
![IMG_20210806_193751](https://user-images.githubusercontent.com/74494691/128511520-13d1fdd2-7e50-49ef-be79-f9b61c1cb6ab.jpg)

**Comment by Tenpi** [comment]
I wasn't able to reciprocate this. I'm going to need more info, otherwise I'm going to close this issue.

![reciprocate1](https://user-images.githubusercontent.com/37512637/128553284-4f666c14-8a7d-496d-a40c-eec6f4ac4d69.png)
