### ISSUE TITLE
Download all Episode Stuck at 37.18%

### ISSUE THREAD

**Issue by hippomu-media** [Tenpi/Crunchyroll-Downloader#24]
![Screenshot_2021-08-06-23-25-09-27_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/74494691/128542431-7e887f9c-d82d-4aaf-9d18-071cff0b4c6a.png)

**Comment by hippomu-media** [comment]
See episode 10
![Screenshot_2021-08-06-23-30-46-07_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/74494691/128542635-e13bb386-7bd1-4db7-8cc5-27cc22d0c85e.png)

**Comment by hippomu-media** [comment]
i can play the video from episode 10 but please see the duration.

Maybe this issue [link](https://github.com/Tenpi/Crunchyroll-Downloader/issues/22) same

![Screenshot_2021-08-06-23-33-25-32_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/74494691/128542957-ea372337-16d3-4733-bc86-2699206a719e.png)

**Comment by Tenpi** [comment]
I wasn't able to reciprocate this. Downloads getting stuck is a known problem (#19), however it's not a bug that I'm able to fix because it's so random. 
![reciprocate2](https://user-images.githubusercontent.com/37512637/128553530-3fb3608c-5a6f-4d51-8491-b9c7eeb1afb1.png)
