### ISSUE TITLE
Increase Download Speed

### ISSUE THREAD

**Issue by hippomu-media** [Tenpi/Crunchyroll-Downloader#25]
Please increase download speed like Internet Download Manager (IDM), i have internet speed 1Gb/s when compared to IDM, IDM is faster with the same large file.

**Comment by Tenpi** [comment]
There is nothing in the code which is limiting the download speed, it's probably based on your network speed as well as CPU speed. You could try messing with the video quality in advanced settings to improve CPU speed, where 0 is lossless and 51 is the worst possible quality.
