### ISSUE TITLE
Download Skipped

### ISSUE THREAD

**Issue by hippomu-media** [Tenpi/Crunchyroll-Downloader#27]
Why i download this episode skipped?
![Screenshot_2021-08-08-01-48-34-52_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/74494691/128611024-559b29a3-0499-4df4-af5e-982e4051b753.png)

**Comment by Tenpi** [comment]
Because you already downloaded it. I skip all the downloads where the destination file already exists for efficiency sake. If for some reason you really want to re-download it, then delete it and try again.
