### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by SAOKT** [Tenpi/Crunchyroll-Downloader#28]
Hello.
How can I choose the chapter to download.
`{seriesTitle}"So I'm a Spider, So What?"/{episodeNumber}"1"`?
I paste it into the program but it doesn't find anything.

**Comment by Tenpi** [comment]
To download the first episode: `So I'm a Spider, So What? 1`
To download all episodes: `So I'm a Spider, So What?`

**Comment by SAOKT** [comment]
Thank you for your work.
