### ISSUE TITLE
Downloading the latest episode of The Great Jahy Will Not Be Defeated

### ISSUE THREAD

**Issue by malzen** [Tenpi/Crunchyroll-Downloader#33]
When I copy the link of ep 5 and paste into downloader it does not download video while as the previous episodes it downloaded them fine.

**Comment by Tenpi** [comment]
It's a premium episode. Do you have CR Premium and are logged in...?

**Comment by malzen** [comment]
Yes

**Comment by Tenpi** [comment]
Fixed @ `v0.3.1`...

You need to use the download button in the browser, because I can only get the video streams from the network traffic. Basically, if you don't use it it will just download the wrong episode.

**Comment by malzen** [comment]
I download the right episode. It is that the episode does not show up in
the downloader when downloading ep 5 of the show. Where as the previous
episodes it picked up quickly on the downloader.
