### ISSUE TITLE
Removed episode titles still get downloaded.

### ISSUE THREAD

**Issue by Serpentstar** [Tenpi/Crunchyroll-Downloader#34]
I noticed that if you download a series and then attempt to review one of the links, it gets removed from the download list but still gets downloaded.  If you already have a folder with an existing episode, the application will delete the existing episode and download it again.

**Comment by Tenpi** [comment]
Might be a bug from when I added the queue system, since the episode might not be properly removed from the queue. I will check it later.

**Comment by Tenpi** [comment]
Fixed as of `v0.3.2`.
