### ISSUE TITLE
Support for Beta URL

### ISSUE THREAD

**Issue by Serpentstar** [Tenpi/Crunchyroll-Downloader#35]
This is a feature request
I would like to see two things:
First, since Crunchyroll is forcing their Beta view down our throats, would it be possible to get support for the new URL scheme?  the new ones do not yield any results.

Second, when we enter a show title without episode, it would be nice to be presented with a list of seasons/episodes that with the option to toggle the download of each one on or off.

Awesome program though.

**Comment by Tenpi** [comment]
It already supports beta URLs. You need to be logged in since you cannot access the beta logged out.

#&#x2060;2 is not a bad idea, but is not trivial to implement. I am not sure if I will add it.

**Comment by Tenpi** [comment]
No plans of adding the second request
