### ISSUE TITLE
Not able to download on your downloader 

### ISSUE THREAD

**Issue by malzen** [Tenpi/Crunchyroll-Downloader#37]
Please could you make a fix for this.

**Comment by Tenpi** [comment]
Not able to download what?

**Comment by malzen** [comment]
Anything on the Beta Crunchyroll website

**Comment by KeronCyst** [comment]
USA here on non-beta CR. This yields NaNs and then a premium warning when paused, even though it's not premium:

https://www.crunchyroll.com/my-hero-academia/episode-64-the-scoop-on-ua-class-1-a-789679

**Comment by Tenpi** [comment]
Closing can't reproduce
