### ISSUE TITLE
I'm being temporarily banned from Crunchyroll

### ISSUE THREAD

**Issue by vicentehenrique1998** [Tenpi/Crunchyroll-Downloader#4]
I'm being banned from Crunchyroll by downloading only one subtitle per episode, only subtitles. The ban lasts a few hours.
This appears on Crunchyroll website:

Error 1015 Ray ID: 5f60a6c96d6509f4 • 2020-11-22 06:39:07 UTC
You are being rate limited
What happened?
The owner of this website (www.crunchyroll.com) has banned you temporarily from accessing this website.

**Comment by Tenpi** [comment]
Hi, approximately how many subtitles did you download? I downloaded all of my hero academia's subs (~88) and didn't get banned. Also, do not use a VPN if you were using one.

**Comment by vicentehenrique1998** [comment]
The new release solve my problem. Thanks!

**Comment by Tenpi** [comment]
Ok, I added a 100ms timeout between downloads. So you (probably) won't be hitting their rate limit anymore.
