### ISSUE TITLE
Certain animes/episodes do not download

### ISSUE THREAD

**Issue by minecraftkiller006** [Tenpi/Crunchyroll-Downloader#40]
For animes that don't change in name (e.g. attack on titan or quintessential quintuplets) the episodes of season 2 and onwards cannot all be downloaded (in AOT's case, none can be downloaded, in quintessential's case, only some can be downloaded; please try to accommodate for these sort of links.

**Comment by lucaslira95** [comment]
Blade Runner: Black Lotus not working here, other animes are ok.

**Comment by Tenpi** [comment]
Cannot reproduce, closing, I have downloaded all the mentioned animes just fine
