### ISSUE TITLE
Progressbar doesnt show up 

### ISSUE THREAD

**Issue by Aghneel** [Tenpi/Crunchyroll-Downloader#43]
![image](https://user-images.githubusercontent.com/41067116/144059789-83e59251-9669-4734-90f5-d3b47f3477e2.png)
im on 0.3.7 OS w10, ETA and progressbar dont show up for some reason but the download is working perfectly

**Comment by Tenpi** [comment]
Do you get this problem on 0.3.6? 0.3.5?

**Comment by Tenpi** [comment]
Fixed on `v0.3.8`
