### ISSUE TITLE
Video quality number meaning

### ISSUE THREAD

**Issue by tormento** [Tenpi/Crunchyroll-Downloader#45]
The title says it all.

I can't find the meaning of video quality, that is defaulted to 16.

How does it work? What number am I supposed to use to have original quality with no recompression?

**Comment by Tenpi** [comment]
That is the Constant Rate Factor, takes a value between 0-51 where lower value results in better quality but increased file size. Anything under CRF16 yields diminishing returns in the sense that the quality difference won't be humanly noticeable, so I do not recommend setting it lower than that.

https://trac.ffmpeg.org/wiki/Encode/H.264
