### ISSUE TITLE
Add AAC as audio format

### ISSUE THREAD

**Issue by Vordlex** [Tenpi/Crunchyroll-Downloader#50]
I would like to ask you to create the option to download the anime with the audio in .aac format instead of just having the .mp3

**Comment by Tenpi** [comment]
Well, I don't want to bloat the options with too many formats that few people will use, and `.aac` is not a widely used format. 

If you really want the audio in `.aac` you can probably download the mp3's and convert them with ffmpeg after. Audio conversions don't take very long.
