### ISSUE TITLE
Download impossible

### ISSUE THREAD

**Issue by Rufh** [Tenpi/Crunchyroll-Downloader#52]
When I have to click see more after the episode list to see the next one, I can't download the anime that appears.
You can try it by following this link:
https://beta.crunchyroll.com/fr/series/G6793XKZY/ancestry-of-a-bookworm
Choose season 6 and click the button at the end of the page to see more episodes.

I tried the same with the old interface from the built-in browser in crunchyroll downloader and I can't download those episodes either.

Thank you for your help.

**Comment by Tenpi** [comment]
Link should be https://beta.crunchyroll.com/series/G6793XKZY/ascendance-of-a-bookworm?
I do not see any show called "Ancestry of a bookworm", its "Ascendance of a bookworm".
Anyways, it worked for me. 
<img width="795" alt="Screen Shot 2022-07-12 at 7 04 02 PM" src="https://user-images.githubusercontent.com/37512637/178613156-49d4796c-0caa-449c-acb1-9e065417e281.png">

**Comment by Rufh** [comment]
Sorry you're right can you also dowload the episode 27 and more ?
Because i can download episode from 1 to 26 but not the epiode above.

**Comment by Tenpi** [comment]
the other eps may not be visible on the page unless you click on "show more", and they're premium-only so you will need crunchyroll premium. Regardless, if u can't get the bulk download to work you could just download the episodes individually.

**Comment by Rufh** [comment]
Thnak you for your answer.
So i have a premium account on Crunchy Roll.
Yes the issue is here, i click on show more and an can see the episodes.
I can watch the episode but i cant download them.
I have tryed to copy the address link and put it in the search field of the downloader but it cant see any file.
I also tryed to use the built-in navigator (logged with my account) and watch the episode then click on the download button on top of the window but it dont work.
So this is why i said there is an issue.
If there is a hint to download these episode can you explain it to me .

Thank you for your help and your time.

**Comment by Tenpi** [comment]
Ok there does seem to a issue with downloading premium episodes on the beta, but i'll look into it later, i'm busy and working on this app isn't a priority. Sorry about that.

**Comment by Tenpi** [comment]
Fixed

**Comment by Rufh** [comment]
Hello, i have tryed the new version but it dont work, or i cant make it work.
![image](https://user-images.githubusercontent.com/59701385/183004727-0a04f11b-ebfb-415e-944c-742a2b91e15f.png)
Here what i do i use the integrated web browser, connect to my account, go to the vidéo, and run it then i press the donwload button but no files appears in the download queue.
I have also tryed to copy the url of the vidéo : 
https://beta.crunchyroll.com/fr/watch/G14U4WJPX/
and put it in the search bar and no effect either.
i'am using the 0.4.3 version.

Thank you for your help.

**Comment by Rufh** [comment]
Here is the steps to reprocude it:
1) launch Crunchyroll Downloader:
![image](https://user-images.githubusercontent.com/59701385/183092652-7813d3ce-b384-437b-94a5-d9328f6d1612.png)
2) Open the intégrated browser : 
![image](https://user-images.githubusercontent.com/59701385/183092880-d68cd419-8857-4e76-9322-8db0c7c2bae1.png)
3) Go to the page of Ascendance of a bookworm than click on 'See More':
![image](https://user-images.githubusercontent.com/59701385/183093201-615922d6-950e-4dab-a840-54f31294ed73.png)
4) At this part next episodes will appears : 
![image](https://user-images.githubusercontent.com/59701385/183093482-81eb16fd-5194-4939-a1ce-34a686d48c26.png)
5) Try to download one of these newly appeared episode like episode 27 :
![image](https://user-images.githubusercontent.com/59701385/183093819-9bf83345-4448-4990-849f-c09b9bcf084e.png)
6) Nothing appears in the download windows.

Here an example when i download the first file:
![image](https://user-images.githubusercontent.com/59701385/183094300-6f55d265-d826-439f-94a9-af1bd0e89b11.png)
We can see the file in the download windows. 

So it work for episodes that appears in first windows (without click on 'See More')
But the episodes that appaers in the 'See More' section cannot be downloaded.

I have found another little bug by testing, the button 'delete all' dont do anything.
![image](https://user-images.githubusercontent.com/59701385/183095562-4f7768ab-0297-438c-8666-044395923607.png)

I hope all the steps are clear.

**Comment by Tenpi** [comment]
I need you to run the development version please, follow these steps:

Install git, Node.js if you don't have them:
https://git-scm.com/downloads
https://nodejs.org/en/ 

The following commands should be run in command line.
Clone the code: `git clone https://github.com/Tenpi/Crunchyroll-Downloader.git`
Move to the folder: `cd Crunchyroll-Downloader`
Install dependencies: `npm install`
Start: `npm start`

Open the development tools by pressing `Ctrl+Shift+I`, then paste whichever errors you are getting here.

**Comment by Rufh** [comment]
Hello, i have encountered an error : 
`$ npm start

> crunchyroll-downloader@0.4.3 start
> npm run clean && webpack && cross-env DEVELOPMENT=true electron dist/main.js


> crunchyroll-downloader@0.4.3 clean
> del-cli ./dist

C:\crdown\Crunchyroll-Downloader\node_modules\loader-runner\lib\LoaderRunner.js:146
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\crdown\Crunchyroll-Downloader\node_modules\webpack\lib\util\createHash.js:144:18)
    at BulkUpdateDecorator.update (C:\crdown\Crunchyroll-Downloader\node_modules\webpack\lib\util\createHash.js:46:50)
    at RawSource.updateHash (C:\crdown\Crunchyroll-Downloader\node_modules\webpack-sources\lib\RawSource.js:64:8)
    at NormalModule._initBuildHash (C:\crdown\Crunchyroll-Downloader\node_modules\webpack\lib\NormalModule.js:752:17)
    at handleParseResult (C:\crdown\Crunchyroll-Downloader\node_modules\webpack\lib\NormalModule.js:816:10)
    at C:\crdown\Crunchyroll-Downloader\node_modules\webpack\lib\NormalModule.js:907:4
    at processResult (C:\crdown\Crunchyroll-Downloader\node_modules\webpack\lib\NormalModule.js:639:11)
    at C:\crdown\Crunchyroll-Downloader\node_modules\webpack\lib\NormalModule.js:691:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.7.0
`

**Comment by Tenpi** [comment]
Use Node.js v16 the newer versions have breaking changes, specifically I use 16.6.2:
https://nodejs.org/dist/v16.6.2/

**Comment by Rufh** [comment]
Here the new error message with the old version of Node.js (i used windows uninstaller to remove it before installing the old version)
`$ npm start

> crunchyroll-downloader@0.4.3 start
> npm run clean && webpack && cross-env DEVELOPMENT=true electron dist/main.js


> crunchyroll-downloader@0.4.3 clean
> del-cli ./dist

(node:2396) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\crdown\Crunchyroll-Downloader\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\crdown\Crunchyroll-Downloader\node_modules\less\lib\less-node\url-file-manager.js:33
                    var message = resp.statusCode === 404
                                       ^

TypeError: Cannot read property 'statusCode' of undefined
    at C:\crdown\Crunchyroll-Downloader\node_modules\less\lib\less-node\url-file-manager.js:33:40
    at done (C:\crdown\Crunchyroll-Downloader\node_modules\needle\lib\needle.js:468:14)
    at ClientRequest.had_error (C:\crdown\Crunchyroll-Downloader\node_modules\needle\lib\needle.js:478:5)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketCloseListener (node:_http_client:420:11)
    at TLSSocket.emit (node:events:406:35)
    at node:net:672:12
    at TCP.done (node:_tls_wrap:580:7)
`

**Comment by Tenpi** [comment]
Ok, just forget it, install the version `v0.4.4` I have enabled the developer tools. Please press `Ctrl+Shift+I` then paste the errors that you are getting.

**Comment by Rufh** [comment]
I got 3 errors : 
`renderer.js:43 GET https://beta.crunchyroll.com/cms/v2/US/M3/crunchyroll/objects/GK9U353XP?locale=fr-FR&Signature=PdWC17ejor4nV-iV8vag0GMeEqwpLOUF1EU1Q-h4g29OjZVwcVNFo23g32uwOFGnwPN-Ck-eEPmGkSXWXjunWrgSUTwFiVw5e0fEWYNwZ~76UA1-vNZhXu8TJsqsXNaG4SsG6KYtzFi-Ga4wTfib3T6-GYZwnFFC6VljRdnxOkDZOo40nwbKW3Yg7wstPf5U8h3uWgO1ZqGgz22hksxQ2Ya8PYx0MgWXnWVj1MyNTTsGez9dPruPfntcJ~yAzwZjbgIy8fowk6E15zeSEnEG4arfZPlKFbOOt5Qd3ojR8iZdYv0dO1Pbhdpc1W9iefecqOWpHvK72ENVbjjOqjwNaw__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLmNydW5jaHlyb2xsLmNvbS9jbXMvdj8vRlIvTTMvY3J1bmNoeXJvbGwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY1OTgxNzc2MX19fV19&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA 403
O @ renderer.js:43
async function (async)
O @ renderer.js:43
U @ renderer.js:43
async function (async)
U @ renderer.js:43
e @ renderer.js:43
emit @ events.js:376
onMessage @ electron/js2c/renderer_init.js:81
renderer.js:43 GET https://beta.crunchyroll.com/cms/v2/US/M3/crunchyroll/objects/GK9U353XP?locale=fr-FR&Signature=PdWC17ejor4nV-iV8vag0GMeEqwpLOUF1EU1Q-h4g29OjZVwcVNFo23g32uwOFGnwPN-Ck-eEPmGkSXWXjunWrgSUTwFiVw5e0fEWYNwZ~76UA1-vNZhXu8TJsqsXNaG4SsG6KYtzFi-Ga4wTfib3T6-GYZwnFFC6VljRdnxOkDZOo40nwbKW3Yg7wstPf5U8h3uWgO1ZqGgz22hksxQ2Ya8PYx0MgWXnWVj1MyNTTsGez9dPruPfntcJ~yAzwZjbgIy8fowk6E15zeSEnEG4arfZPlKFbOOt5Qd3ojR8iZdYv0dO1Pbhdpc1W9iefecqOWpHvK72ENVbjjOqjwNaw__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLmNydW5jaHlyb2xsLmNvbS9jbXMvdj8vRlIvTTMvY3J1bmNoeXJvbGwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY1OTgxNzc2MX19fV19&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA 403
I @ renderer.js:43
async function (async)
I @ renderer.js:43
U @ renderer.js:43
async function (async)
U @ renderer.js:43
e @ renderer.js:43
emit @ events.js:376
onMessage @ electron/js2c/renderer_init.js:81
VM141:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0`

**Comment by Tenpi** [comment]
Ok, I finally have a better idea of what the problem is it looks like you are getting a 403 (forbidden) error when trying to access the episode streams.

Just to be clear, you aren't from the US right? Does the URL work if you change the https://beta.crunchyroll.com/cms/v2/US/M3/crunchyroll/objects/ to https://beta.crunchyroll.com/cms/v2/FR/M3/crunchyroll/objects/ ?

You can also try deleting the cookies and logging in again.

**Comment by Rufh** [comment]
Yes i am in France and not US.
I dont think i have weel understand but i have take the long URL in the error message and change the US by FR.
I have Json message : 
`<html><body>
<div id="content"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><input class="searchBox devtools-filterinput" placeholder="Filtrer le JSON"></div><div class="panelContent">

  |  
-- | --
__class__ | "collection"
__href__ | "/cms/v2/FR/M3/crunchyroll/objects/GK9U353XP"
__resource_key__ | "cms:/objects/GK9U353XP"
__links__ | {}
__actions__ | {}
total | 1
items |  
0 |  
__class__ | "panel"
__href__ | ""
__links__ |  
episode/season |  
href | "/cms/v2/FR/M3/crunchyroll/seasons/G69VQ1M8Y"
episode/series |  
href | "/cms/v2/FR/M3/crunchyroll/series/G6793XKZY"
resource |  
href | "/cms/v2/FR/M3/crunchyroll/episodes/GK9U353XP"
resource/channel |  
href | "/cms/v2/FR/M3/crunchyroll/channels/crunchyroll"
streams |  
href | "/cms/v2/FR/M3/crunchyroll/videos/G3WFX0X9J/streams"
__actions__ | {}
id | "GK9U353XP"
external_id | "EPI.843024"
channel_id | "crunchyroll"
title | "Chapitre vingt-sept – Le début de l’hiver"
description | "L’incorrigible Maïn est censée lever le pied et passer l’hiver au temple tranquillement, sans rien inventer ou faire fabriquer quoi que ce soit. Comme on peut s’en douter, à la première occasion, elle va se lancer un nouveau défi, et pas n’importe lequel."
promo_title | ""
promo_description | ""
type | "episode"
slug | ""
slug_title | "the-beginning-of-winter"
images |  
thumbnail |  
0 |  
0 |  
width | 320
height | 180
type | "thumbnail"
source | "https://beta.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/9f4f80e8f5bf26b19f50887ca35a520b.jpeg"
1 |  
width | 600
height | 338
type | "thumbnail"
source | "https://beta.crunchyroll.com/imgsrv/display/thumbnail/600x338/catalog/crunchyroll/9f4f80e8f5bf26b19f50887ca35a520b.jpeg"
2 |  
width | 640
height | 360
type | "thumbnail"
source | "https://beta.crunchyroll.com/imgsrv/display/thumbnail/640x360/catalog/crunchyroll/9f4f80e8f5bf26b19f50887ca35a520b.jpeg"
3 |  
width | 800
height | 450
type | "thumbnail"
source | "https://beta.crunchyroll.com/imgsrv/display/thumbnail/800x450/catalog/crunchyroll/9f4f80e8f5bf26b19f50887ca35a520b.jpeg"
4 |  
width | 1200
height | 675
type | "thumbnail"
source | "https://beta.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/9f4f80e8f5bf26b19f50887ca35a520b.jpeg"
5 |  
width | 1440
height | 810
type | "thumbnail"
source | "https://beta.crunchyroll.com/imgsrv/display/thumbnail/1440x810/catalog/crunchyroll/9f4f80e8f5bf26b19f50887ca35a520b.jpeg"
6 |  
width | 1600
height | 900
type | "thumbnail"
source | "https://beta.crunchyroll.com/imgsrv/display/thumbnail/1600x900/catalog/crunchyroll/9f4f80e8f5bf26b19f50887ca35a520b.jpeg"
7 |  
width | 1920
height | 1080
type | "thumbnail"
source | "https://beta.crunchyroll.com/imgsrv/display/thumbnail/1920x1080/catalog/crunchyroll/9f4f80e8f5bf26b19f50887ca35a520b.jpeg"
episode_metadata |  
series_id | "G6793XKZY"
series_title | "Ascendance of a Bookworm"
series_slug_title | "ascendance-of-a-bookworm"
season_id | "G69VQ1M8Y"
season_title | "Ascendance of a Bookworm"
season_slug_title | "ascendance-of-a-bookworm"
season_number | 6
episode_number | 27
episode | "27"
sequence_number | 27
duration_ms | 1420095
episode_air_date | "2022-04-12T02:29:00+09:00"
upload_date | "2022-04-12T02:29:00+09:00"
availability_starts | "2022-04-11T18:30:00Z"
availability_ends | "9998-11-30T08:00:00Z"
eligible_region | "FR"
is_premium_only | true
extended_maturity_rating | {}
maturity_ratings |  
0 | "TV-14"
is_mature | false
mature_blocked | false
available_date | null
free_available_date | "2022-04-11T18:30:00Z"
premium_date | null
premium_available_date | "2022-04-11T18:30:00Z"
is_subbed | true
is_dubbed | false
is_clip | false
available_offline | true
subtitle_locales |  
0 | "en-US"
1 | "es-419"
2 | "es-ES"
3 | "fr-FR"
4 | "pt-BR"
5 | "ar-SA"
6 | "it-IT"
7 | "de-DE"
8 | "ru-RU"
availability_notes | ""
audio_locale | ""
versions | null
closed_captions_available | false
playback | "https://pl.crunchyroll.com/asset/c4b8ed1e8755ff23b0ec1922d5f01c3b/v/e09f3f57faaf219199b323c5036071cd/languages/en-US,es-419,es-ES,fr-FR,pt-BR,ar-SA,it-IT,de-DE,ru-RU,es-LA,ar-ME?*&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vYXNzZXQvYzRiOGVkMWU4NzU1ZmYyM2IwZWMxOTIyZDVmMDFjM2Ivdi9lMDlmM2Y1N2ZhYWYyMTkxOTliMzIzYzUwMzYwNzFjZC8~KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY1OTkwNTM3MX19fV19&Signature=IVErqDkF1te40qZIG5wbW83Xq~zeM~AHLYELBAdW43swDQl33QLLInOh07tNbuWwhSVzYlqlg5xuokUmSwyaQ-iiGM5C1gurVKaX4aFJcGr3kKEqnHOkcozieDxSbXyzEfkVMa0tOkxn8pRbiQ0UnICoZ4ZNx2ZFAJWNCDeW-NnqXVDljsHcAGWRCQdE62B3EfyazTNCtbiMpQ4k0SWZhmu5k894SJUZBD2aVqilso8LTekC35EyTCkQDiWGipVJKKUP85O5nCT2d3FNtoD4Ha1gjfIsXPWNb4kPcE6B6a~YkFvbhxbrelQ5W0MGEYxDpOyr0AINkdsTDEyMK~-BHw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA"
linked_resource_key | "cms:/episodes/GK9U353XP"

</div></div></div></div>
</body>
</html>`

**Comment by Rufh** [comment]
I add this.
When i use the url with US i got this messge:
`<Error>
<Code>AccessDenied</Code>
<Message>Access denied</Message>
</Error>`

**Comment by Tenpi** [comment]
Ok, please update to `v0.4.5` then go to the advanced settings and change the region from "US" to "FR". Please let me know if that fixes the issue, otherwise paste any other errors that you are getting.

**Comment by Rufh** [comment]
Ho, finally it works !
![image](https://user-images.githubusercontent.com/59701385/183207598-050ca739-aca9-475f-8b7c-19bf45e9bda3.png)

Thank you.

**Comment by Tenpi** [comment]
> Thank you.
> 
> One more thing, the button delete all dont work.

No problem! The delete all button is working for me but would you mind creating another issue for it? I want to keep different bugs on separate issues

**Comment by Rufh** [comment]
Perhaps is my mystake.
Is the delete button, delete (remove) all the download in the queue, or it is other thing ?

**Comment by Tenpi** [comment]
The delete all button stops all in-progress downloads and then deletes all the episodes visible in the UI from the filesystem.

**Comment by Rufh** [comment]
Hello,
I have installed the latest version 0.4.7 and the bug seems to be back.
The setting for the region has also disapered.
Do i have to open a new ticket ?

Thank you.
