### ISSUE TITLE
bug to start appimage and "waiting"  permanently but not downloading

### ISSUE THREAD

**Issue by gego51** [Tenpi/Crunchyroll-Downloader#53]
I'm use Debian Gnu-Linux testing (Bookworm) 
![bug](https://user-images.githubusercontent.com/5407223/180867507-6335a3b7-0b54-4cf3-8aa7-32a675a44541.png)
![bug2](https://user-images.githubusercontent.com/5407223/180867517-5a97d6c5-610e-4e3a-a915-944f0911791f.png)
)

**Comment by Tenpi** [comment]
it says your file system is read-only, the app needs permissions to write to the filesystem
