### ISSUE TITLE
Unable to download with beta site

### ISSUE THREAD

**Issue by Juliedelyon** [Tenpi/Crunchyroll-Downloader#54]
Hello,

First of all, thank you very much for developing this app for anime fans. It is very precious! Thank you so much!
I allow myself to contact you also because since the transition to the crunchyroll beta site, the download has unfortunately become impossible. I am well aware that your time must be precious but I allow myself this message in order to inform you of the problem and in case you can take a look!

Many thanks again.

Julie

**Comment by MK1338** [comment]
I can confirm that since Beta version is now **Forced** and the **only version** available, it became impossible to download

**Comment by MK1338** [comment]
Hi,
Is it supposed to be fixed because i still can't download. Nothing happens when i use this.
Link : https://beta.crunchyroll.com/fr/watch/G4VUQJ79W/surpass-the-emperor-of-the-sea-luffy-strikes-back-with-an-iron-fist

**Comment by Juliedelyon** [comment]
Thank you very much for your help.
I will try!
Best Regards.
Julie
