### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by Vordlex** [Tenpi/Crunchyroll-Downloader#55]
It returns me those errors when I try to download episodes like https://beta.crunchyroll.com/pt-br/watch/G14U40J5P/remember-to-keep-a-clear-head-in-difficult-times and many others (I'm logged and I have premium)

![image](https://user-images.githubusercontent.com/43836184/183479762-c43ba090-6283-4f2f-ab90-15e5b820ab2b.png)
![image](https://user-images.githubusercontent.com/43836184/183479788-e521d780-c16b-4f20-a7f9-5b3f5e978d2c.png)

**Comment by Tenpi** [comment]
BR is the region for Brazil. Are you located in Brazil, or are you using a Brazilian VPN/proxy? (That will not work - you need to download from the same region your account is in).

**Comment by Vordlex** [comment]
I'm from Brazil and I'm not using any kind of VPN/proxy, I can access the episode normaly, and my account is located in Brazil.

**Comment by Tenpi** [comment]
Then change the BR in the link to any of these possible regions and tell me which one works.
```
US
GB
ES
LA
FR
DE
IT
RU
PT
ME
JP
```

**Comment by Vordlex** [comment]
My error was solved when I uninstalled the app (with revo uninstaller to make sure that it will remove all registry) and installed again. The BR region on link was right.
