### ISSUE TITLE
Not Downloading

### ISSUE THREAD

**Issue by ARCHANGELMANGA** [Tenpi/Crunchyroll-Downloader#56]
So im trying to use this after the update and when i enter a link it doesnt add the download

it was working for me before the update

**Comment by Vordlex** [comment]
can you press ctrl+shift+i and show what is the error on console and network tab?

**Comment by ARCHANGELMANGA** [comment]
![image](https://user-images.githubusercontent.com/110497712/184135139-ce5eb499-1a0e-4f91-bc13-67bdca0b9e60.png)

this is the error im seeing

**Comment by Vordlex** [comment]
I made a bugfix for that, you need to wait for the pull request ou clone my fork and build the app

**Comment by ARCHANGELMANGA** [comment]
okay ill just have to wait. i dont have enough knowledge with any of that lol
