### ISSUE TITLE
[BUG] Cannot download on MacOS version

### ISSUE THREAD

**Issue by TutifrutiDEV** [Tenpi/Crunchyroll-Downloader#59]
Hello,
I have a problem when i try to find and download an episode, as you can see in the console here there is some problems :

![image](https://user-images.githubusercontent.com/64048607/186523567-80756f33-7375-4a39-842b-489cff273028.png)
The denied url: 
`https://beta.crunchyroll.com/cms/v2/FR/M3/crunchyroll/objects/G0DUN1W5G?locale=fr-FR&Signature=k6aWHPqYPOIfLoMGaY4OJLadNBPL~WE40VAYb7grdlnVBte67qjgGeyv~lCvDeNiUg1fomHbe8bKL-c7leRynyfsNptvPs2VTaeEDojdERFVFA55-okAx49IObsFN-vNPXEfbLJc6qHzTkaHHHK7npIShNnWJIigKxpyWQISEftgCSJPHqCzjC6HM3oVrctrvJAjgxj~kdWpaonJkj9fIXJEbX-XAIiQ079XNFLeNFRpVvZw6LKe80ijZrrp9Efc56JhJVZx62rJymNcCxtGxwBAzkEt~7XmbAUNA7SV1-vW~R3D2uQf5fJ8ywey2TioXudzU8tUVglBviDmmLn9WA__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLmNydW5jaHlyb2xsLmNvbS9jbXMvdj8vRlIvTTMvLS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjYxNDU4MzQ3fX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA`

I hope you will be able to fix it 😄  
Thank you in advance for your help !

**Comment by Tenpi** [comment]
Replace the FR in the link with any of these other regions and tell me which one works:
```
US
GB
ES
LA
DE
IT
RU
PT
BR
ME
JP
```

**Comment by Tenpi** [comment]
Go to the crunchyroll website in a browser (not the app), go to any episode page and press `Ctrl+Shift+I` to open the developer tools. Go to the network tab and find the request that looks like this, and tell me what it is.
<img width="884" alt="Screen Shot 2022-08-25 at 11 57 51 AM" src="https://user-images.githubusercontent.com/37512637/186713926-638bb163-d221-4fc5-8649-fafe2d11f24a.png">

**Comment by TutifrutiDEV** [comment]
![image](https://user-images.githubusercontent.com/64048607/186757847-a6f112f7-7a14-4d62-865c-f7742fc97055.png)
I guess this is this one :)

**Comment by Tenpi** [comment]
Upgrade to `v0.4.8` and let me know if it works.

**Comment by TutifrutiDEV** [comment]
Yes! this issue is solved, I guess I have one last problem, I hope you will be able to solve it, sorry to be so boring
This time, the episode is in waiting, I've tried other random free episodes, and it's the same, idk why, I have the concurrent downloads set to 12 on my settings page
<img width="1702" alt="image" src="https://user-images.githubusercontent.com/64048607/186764591-55faec60-4804-4007-8309-c1755fc268a5.png">
Thank you for your big help!

**Comment by Tenpi** [comment]
Open the developer tools and post the errors. If there isn't any errors, than do a clean re-installation. 

On MacOS, you will have to delete all the files in the following locations manually.
`/Library/Application Support/crunchyroll-downloader`
`~/Library/Application Support/crunchyroll-downloader`

**Comment by TutifrutiDEV** [comment]
Sorry for the delay, it's solved :) thank a lot for your help !
