### ISSUE TITLE
Output Template Option

### ISSUE THREAD

**Issue by vicentehenrique1998** [Tenpi/Crunchyroll-Downloader#6]
Can you add a way to make custom names for the files?
Like youtube-dl or CR-dl from DasKraken.

**Comment by Tenpi** [comment]
Uh... maybe? I don't see much of a point in it.

**Comment by vicentehenrique1998** [comment]
Please do it. I would be very grateful.
If it's not too much to ask, do it with folders too. It would make my life much easier.

**Comment by Tenpi** [comment]
Added in `v0.1.5`, below are the available replacements.

{seasonTitle} - The title of the season
{episodeTitle} - The title of the episode
{seriesTitle} - The title of the series (ex. The series of SAO II is "Sword Art Online")
{episodeNumber} - The number of the episode
{resolution} - The resolution, excluding the "p". Only available for video formats.

Use slashes to indicate sub-folders, eg. `{seriesTitle}/{seasonTitle}/{episodeTitle}`.

**Comment by vicentehenrique1998** [comment]
Thanks a lot.
