### ISSUE TITLE
ERROR TO DOWNLOAD M3U8

### ISSUE THREAD

**Issue by JuanF007** [Tenpi/Crunchyroll-Downloader#60]
When you want to download in m3u8 format
the file is less than 100kb and can't play on vlc

**Comment by Tenpi** [comment]
m3u8 is a text file with all the links to the video stream, VLC can play it but you need an internet connection.

If you want to play the videos without an internet connection you need to pick mp4/mkv. The primary reason why you would pick m3u8 instead is that you will save a LOT of disk.
