### ISSUE TITLE
Series download error

### ISSUE THREAD

**Issue by Pipixel** [Tenpi/Crunchyroll-Downloader#61]
Hi,
When I put the link of a complete series like this one _https://beta.crunchyroll.com/fr/series/G4PH0WXVJ_
I get this error message, even with the name. However, the links of the episodes one by one works perfectly

![image](https://user-images.githubusercontent.com/66361896/189535892-938ab535-fa73-4ad3-8bd7-bd6c97270eb9.png)

**Comment by Tenpi** [comment]
Post full html of this link: https://beta.crunchyroll.com/fr/series/G4PH0WXVJ 
on https://pastebin.com, post the link.

**Comment by Pipixel** [comment]
I cannot use Pastbin for some curious so here's a link from an alternative https://www.klgrth.io/paste/ohhko

**Comment by Tenpi** [comment]
Update

**Comment by Pipixel** [comment]
Thanks for the update but it doesn't work and I get these errors messages even after deleting the cookies

![image](https://user-images.githubusercontent.com/66361896/191957524-d9e6685a-0112-4163-8833-77e1abca2299.png)

**Comment by Tenpi** [comment]
Update

**Comment by Pipixel** [comment]
nothing change, there is the same error

**Comment by Tenpi** [comment]
> It's work only via browser download, not for the link in the textbox

Error message? And also show where in the code the error occurred.

**Comment by Pipixel** [comment]
here's what I get with the link directly
![image](https://user-images.githubusercontent.com/66361896/191974143-23be3311-e49f-4546-8127-a826a82bfbda.png)

I forgot it doesn't work with the title, it gave this message
![image](https://user-images.githubusercontent.com/66361896/191975347-570ff197-1211-4f61-ad26-cdb57fded470.png)

**Comment by Tenpi** [comment]
Ok, nvm, the episodes are no longer in the html and are generated dynamically with javascript, so this is a browser-only bugfix sorry. Marking as can't be fixed. 

Titles no longer work because they use the original api that no longer works, I might try to update it to the new beta api in the future.
