### ISSUE TITLE
Episode Download Error

### ISSUE THREAD

**Issue by Morgul** [Tenpi/Crunchyroll-Downloader#62]
When I attempt to download the series "My Dressup Darling", only the first 10 episodes start to download. I can individually download every missing episode, except for 11, which gives this error:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/770655/190936193-bca4e0ac-267c-42c0-9565-089517a55442.png">

(link: https://beta.crunchyroll.com/watch/GWDU8585D/i-am-currently-at-a-love-hotel)

(Also, if there's an error with one episode, the rest of the series should probably still download.)

**Comment by Morgul** [comment]
As a follow up, it looks like this only happens if I'm doing `mkv` (Makes sense, it's complaining about subtitles). I ran the dev version and did some poking in the code, and the problem seems to be here:

https://github.com/Tenpi/Crunchyroll-Downloader/blob/master/components/SearchBar.tsx#L327

I'll keep poking as I have free time, and if I come up with anything like a good solution, I'll throw up a PR.

If anyone's having this same issue, though, just switch to mp4 and the issue should go away.

**Comment by Tenpi** [comment]
Post full html of this link: https://beta.crunchyroll.com/watch/GWDU8585D/i-am-currently-at-a-love-hotel 
on https://pastebin.com/, post the link.

**Comment by VanStorm** [comment]
> Post full html of this link: https://beta.crunchyroll.com/watch/GWDU8585D/i-am-currently-at-a-love-hotel on https://pastebin.com/, post the link.

Done that for you:
https://pastebin.com/K2tEU38n

**Comment by Tenpi** [comment]
Not tested but it should be fixed.
