### ISSUE TITLE
Feature Suggestion: Automatically click 'Show More' button

### ISSUE THREAD

**Issue by Morgul** [Tenpi/Crunchyroll-Downloader#63]
Just something I noticed while using the downloader. (Thanks, btw. This thing is great! 😁)

When loading a show page like, for example, https://beta.crunchyroll.com/series/GR9PKENW6/yu-yu-hakusho, If you click the download button on the browser, it will download only the episodes currently showing. If you want the full series, you need to click the 'Show More' link on the page first, then the download button.

It would be nice if that second step wasn't required.

**Comment by Tenpi** [comment]
Added
