### ISSUE TITLE
Slahes in episode names cause folders to be created.

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#66]
Please trim folder names as trailing spaces are a real pain to delete in Windows Explorer.

When the episode name has a / character in it these get parsed as folders. As such this program creates folders with a space at the beginning/end if there is one in the name.
If you are using mkdirs perhaps parse with a simple regex looking for / with a preceding space

**Comment by Tenpi** [comment]
Fixed

**Comment by ElgarL** [comment]
Thank you, however this broke all folder creation.

I'm using an output of `{seriesTitle}/{seasonTitle}/E{episodeNumber} - {episodeTitle}`

**Comment by Tenpi** [comment]
I didn't test this because of how trivial it was, but ofc I messed it up. It should be fixed now.
