### ISSUE TITLE
Feature request - remember window locations.

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#67]
I've been using this program a bit now and loving it, however, the only annoying thing is having to resize the main and browser windows every time. Would it be possible for you to have the positions/sizes remembered between sessions?

**Comment by Tenpi** [comment]
I save the window sizes not positions, I prefer it always opens around the center of the screen.

**Comment by ElgarL** [comment]
Almost works. It does need to save the position too, however it has a bug.
It resets to default on the third opening.

**Comment by Tenpi** [comment]
Update and see if that works.

**Comment by ElgarL** [comment]
Remembering size is now perfect. If it remembered window location it would be 100%.

**Comment by Tenpi** [comment]
Like I said I prefer that it opens in the center, plus if I remember the position, if you move it off-screen and close it it will make the app unusable and you will need to reinstall it. It's possible to avoid with extra code but is a bit annoying so I'll mark the rest of this as won't add.
