### ISSUE TITLE
[BUG] Some episodes cannot be downloaded

### ISSUE THREAD

**Issue by IvanMazzoli** [Tenpi/Crunchyroll-Downloader#70]
I was trying to get some episodes of JoJo but, for some reason, there are episodes that I can't download.
With some trial and error I've found out that episodes with commas in their title fails to be downloaded via direct link.

For example those episodes works:
• https://www.crunchyroll.com/it/jojos-bizarre-adventure/episode-18-head-to-venice-780980
• https://www.crunchyroll.com/it/jojos-bizarre-adventure/episode-22-the-g-in-guts-782558
But those don't:
• https://www.crunchyroll.com/it/jojos-bizarre-adventure/episode-30-green-tea-and-sanctuary-part-1-783787
• https://www.crunchyroll.com/it/jojos-bizarre-adventure/episode-16-the-thankful-death-part-2-780978

Other symbols such as " or ! doesn't seem to have any impact.

Screenshots of the developer console + network:.
![image](https://user-images.githubusercontent.com/7896815/193908568-514cc55a-a3d0-4534-b49f-5f00f980f789.png)
![image](https://user-images.githubusercontent.com/7896815/193908646-7ddf93e7-208e-41e5-8737-8659bbdd4588.png)

**Comment by Tenpi** [comment]
JoJo is not available in the US, so find a reproducible episode which I can see.

**Comment by IvanMazzoli** [comment]
I found out that I can download other episodes even if it has commas in the title:
• https://www.crunchyroll.com/it/boruto-naruto-next-generations/episode-228-kawakis-path-to-becoming-a-ninja-821072
• https://www.crunchyroll.com/it/naruto/episode-177-please-mr-postman-526686
It seems that only JoJo is having problems so far...

**Comment by IvanMazzoli** [comment]
The 400 response is given by this URL:
https://www.crunchyroll.com/it/jojos-bizarre-adventure/episode-30-green-tea-and-sanctuary-part-1-783787/episode-285-jojos-bizarre-adventure-golden-wind-destino-782565/%22%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cimg%20class=/%22mug/%22%20src=/%22https:////img1.ak.crunchyroll.com//i//spire1-tmb//853ac983580dc3799b3b3bed1acd84d31556851077_wide.jpg/%22%20alt=/%22JoJo's%20Bizarre%20Adventure%20Episodio%2028.5/%22%20//%3E/n%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=/%22collection-carousel-overlay/%22%20dir=/%22auto/%22%3E/n/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20class=/%22collection-carousel-overlay-top%20ellipsis/%22%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20Episodio%2028.5%20%20%20%20%20%20%20%20%20%20%20%20%3C//span%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20class=/%22collection-carousel-overlay-bottom%20ellipsis%20xsmall-margin-bottom/%22%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Le%20bizzarre%20avventure%20di%20GioGio%20Vento%20Aureo%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C//span%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20/n%20%20%20%20%20%20%20%20%20%20%3C//div%3E/n/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=/%22episode-progress-bar/%22%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=/%22episode-progress/%22%20media_id=/%22782565/%22%20style=/%22width:0%;/%22%3E%3C//div%3E/n%20%20%20%20%20%20%20%20%20%20%3C//div%3E/n%20%20%20%20%20%20%20%20%3C//a%3E/n%20%20%20%20%20%20%3C//div%3E/n%20%20%20%20%3C//div%3E/n/n%20%20%20%20/n%20%20%20%20%3Cscript%20type=/%22text//javascript/%22%3E/n%20%20%20%20%20%20$('.collection-carousel-contents%20div[media_id=782565]%20.hover-bubble').data('bubble_data',%7B/%22name/%22:/%22Le%20bizzarre%20avventure%20di%20GioGio%20Vento%20Aureo/%22,/%22description/%22:/%22Ripercorriamo%20la%20storia%20finora!/%22%7D);/n%20%20%20%20%20%20%20%20%20%20%3C//script%3E/n%20%20%20%20%22,%22783786%22:%22%20%20%20%20%3Cdiv%20class=/%22collection-carousel-media-link%20/%22%3E/n%20%20%20%20%20%20%3Cdiv%20class=/%22collection-carousel-media-thumb%20hover-bubble/%22%3E/n%20%20%20%20%20%20%20%20%3Ca%20class=/%22link%20block-link%20block/?skip_wall=1
No clue if that's normal or not 

Here's the HTML content of the CR page, had to create a Gist due to Pastebin so called "SMART" filters blocking the contents https://gist.github.com/IvanMazzoli/111471b0f01ea536cd421c74b306748d

**Comment by Tenpi** [comment]
Probably fixed, but a shot in the dark because I can't see this episode.

**Comment by IvanMazzoli** [comment]
I tried the new version and, unfortunately, it still doesn't work. The error 400 it's still there and the URL doesn't seem to have changed, just in case here it is:

https://www.crunchyroll.com/it/jojos-bizarre-adventure/episode-30-green-tea-and-sanctuary-part-1-783787/episode-285-jojos-bizarre-adventure-golden-wind-destino-782565/%22%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cimg%20class=/%22mug/%22%20src=/%22https:////img1.ak.crunchyroll.com//i//spire1-tmb//853ac983580dc3799b3b3bed1acd84d31556851077_wide.jpg/%22%20alt=/%22JoJo's%20Bizarre%20Adventure%20Episodio%2028.5/%22%20//%3E/n%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=/%22collection-carousel-overlay/%22%20dir=/%22auto/%22%3E/n/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20class=/%22collection-carousel-overlay-top%20ellipsis/%22%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20Episodio%2028.5%20%20%20%20%20%20%20%20%20%20%20%20%3C//span%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20class=/%22collection-carousel-overlay-bottom%20ellipsis%20xsmall-margin-bottom/%22%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Le%20bizzarre%20avventure%20di%20GioGio%20Vento%20Aureo%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C//span%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20/n%20%20%20%20%20%20%20%20%20%20%3C//div%3E/n/n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=/%22episode-progress-bar/%22%3E/n%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=/%22episode-progress/%22%20media_id=/%22782565/%22%20style=/%22width:0%;/%22%3E%3C//div%3E/n%20%20%20%20%20%20%20%20%20%20%3C//div%3E/n%20%20%20%20%20%20%20%20%3C//a%3E/n%20%20%20%20%20%20%3C//div%3E/n%20%20%20%20%3C//div%3E/n/n%20%20%20%20/n%20%20%20%20%3Cscript%20type=/%22text//javascript/%22%3E/n%20%20%20%20%20%20$('.collection-carousel-contents%20div%5Bmedia_id=782565%5D%20.hover-bubble').data('bubble_data',%7B/%22name/%22:/%22Le%20bizzarre%20avventure%20di%20GioGio%20Vento%20Aureo/%22,/%22description/%22:/%22Ripercorriamo%20la%20storia%20finora!/%22%7D);/n%20%20%20%20%20%20%20%20%20%20%3C//script%3E/n%20%20%20%20%22,%22783786%22:%22%20%20%20%20%3Cdiv%20class=/%22collection-carousel-media-link%20/%22%3E/n%20%20%20%20%20%20%3Cdiv%20class=/%22collection-carousel-media-thumb%20hover-bubble/%22%3E/n%20%20%20%20%20%20%20%20%3Ca%20class=/%22link%20block-link%20block/?skip_wall=1

**Comment by Tenpi** [comment]
I don't need that. Is this a singular episode download or are you downloading the whole series? Are you using the browser or pasting in the link?

**Comment by IvanMazzoli** [comment]
I'm trying to download just a couple of episodes. I tried both pasting links from CrunchyRoll (beta and non beta) and via the internal browser but none works. Haven't tried to download the whole serie, 176 episodes are a little too much for my internet connection 🤕

**Comment by Tenpi** [comment]
Update again

**Comment by IvanMazzoli** [comment]
Unfortunately still doesn't work. This time no errors in console

**Comment by Tenpi** [comment]
I'm not going to continue to bother with this, unless you can find an episode that's available in the US with this issue it won't be fixed, sorry.
