### ISSUE TITLE
Download Errors

### ISSUE THREAD

**Issue by todstelzer** [Tenpi/Crunchyroll-Downloader#71]
Hello,
I can´t download anything anymore. This Screenshot is from a episode download with build in  browser extension of the CR Downloader.
German site no VPN. Tried it on a different computer as well.
Searching for Anime don´t find anything anymore.
Can watch episodes just fine with in build browser.
De-installed and tried different versions too. Deleted files in %Appdata% too.  
Tried going online with my phone connection in case my network is no good but still the same errors.

https://www.crunchyroll.com/de/watch/G0DUN19JG/complicated-convoluted-perplexing-honest-feelings

![grafik](https://user-images.githubusercontent.com/67606371/196760759-f7800d57-9ef6-461b-8afa-53c1b60664e1.png)
![grafik](https://user-images.githubusercontent.com/67606371/196762339-a6895951-c451-4544-a7d9-17496ab0f61e.png)

**Comment by Marco-9456** [comment]
This is because Crunchyroll updated there website
and beta.Crunchyroll dose not exist anymore.
Lets hope @Tenpi sees this and fix it

**Comment by Marco-9456** [comment]
> I hope it´s fixable. I can record it via HDMI recording but it´s a pain to record it this way.

it's fixable, this is also happening with yt-dlp
