### ISSUE TITLE
Download not working since 0.6.1

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#73]
Hitting the download button or a direct download link does nothing since 0.6.1

**Comment by Tenpi** [comment]
There was no code changes other than removing the beta, I suggest that you reinstall.

**Comment by ElgarL** [comment]
Uninstalled, deleted folder in %appdata% and reinstalled.

Pasting a single file link works fine (https://www.crunchyroll.com/watch/G7PU4VV80/lightning-of-rage-vs-friends)
Pasting a series link, or clicking the download icon on the built in browser does nothing (https://www.crunchyroll.com/series/GRE50KV36/black-clover) I also tried (https://www.crunchyroll.com/series/GVDHX8JJE/black-summoner) to no avail.

**Comment by Tenpi** [comment]
Pasting link of series is no longer supported, and I will not fix it. (#61)

**Comment by ElgarL** [comment]
So how do we download a series now? Clicking the download button on the browser does nothing either.
Are we supposed to download every episode individually?

**Comment by Tenpi** [comment]
The series download still works fine through the browser, including Black Clover and Black Summoner. It just takes awhile for it to load 170 episodes. If it's not working for you, then you should reinstall and delete the cookies. If that doesn't work, then post the error messages, I cannot do anything with "it doesn't work" when I can clearly see it working on my end.

<img width="788" alt="スクリーンショット 2022-10-22 午後3 30 19" src="https://user-images.githubusercontent.com/37512637/197359161-955bc99c-8093-46fa-abff-8186e6e14ded.png">

**Comment by ElgarL** [comment]
Where do I find any error messages? I literally see nothing when I click the download button.

**Comment by Tenpi** [comment]
`Ctrl+Shift+I`

I checked the code and yeah, it's the same as it was before. If anything changed it is on CR's side. If they started to throttle the requests I don't think I can do anything, you will just have to wait it out.

**Comment by ElgarL** [comment]
Ok I'll leave it at that. Thanks for listening.
