### ISSUE TITLE
Install on Windows requires Admin login?

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#79]
Must be a bug as No program requires Administrator rights to install, unless it's doing something nefarious.

**Comment by Tenpi** [comment]
By default it will install in `C:/Program Files` which will always require Administrator rights because that is a protected location. The program itself doesn't use admin rights unless you open it as administrator. Although I could build an installer that doesn't ask, it causes issues for people installing to the default location.

**Comment by ElgarL** [comment]
I don't install to the default location so it was odd for it to even ask as my UAC is disabled.
MY C drive is only for OS, all Programs go on a different drive. It also won;t go past the login prompt, even if I say to use the current user.

**Comment by Tenpi** [comment]
Maybe you can follow this to run it without elevated permissions without me making a new version:
https://superuser.com/questions/171917/force-a-program-to-run-without-administrator-privileges-or-uac

**Comment by ElgarL** [comment]
That registry hack allows it to install, but fails to run. You seem to be doing something odd in this version. This is just a wrapper for ffmpeg, theres no way it needs these hacks/access rights to install and run.

![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/2d14a120-438b-4d3e-8c8d-dacd18fe9a9a)

**Comment by Tenpi** [comment]
Looks like your OS is too old the newest versions of Chromium dropped support for Windows older than 10, which don't have `DiscardVirtualMemory`. I will see if I can downgrade, if it doesn't cause too many issues.

**Comment by ElgarL** [comment]
Yeah I run Win7 on most of my boxes. Newer OS's offer nothing I want and plenty I don't.

**Comment by Tenpi** [comment]
Probably fixed in `v0.6.9`
