### ISSUE TITLE
Download seems to not be working Win 11

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#80]
I installed on a Win 11 test machine. Logged in to CR in both the downloader browser and Firefox (my default browser).
Opened an anime <https://www.crunchyroll.com/series/GYQ4ZWV46/in-another-world-with-my-smartphone>
Clicked the download button
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/2dbf7df8-81c1-485c-9097-3291d309b844)
With settings of
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/fb7eb79e-f331-458d-b7ee-abcd87124c3e)
and nothing happens. Is there is a log I can pull up for you?

**Comment by Tenpi** [comment]
Press Ctrl+Shift+I and show me the errors (if any). I can download it but it only 720p is available the 1080p version has drm.

**Comment by ElgarL** [comment]
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Z (renderer.js:43:235152)
    at async Promise.all (index 1)
    at async Y (renderer.js:43:237321)
    at async renderer.js:43:242873
    at async re (renderer.js:43:242462)
www.crunchyroll.com/content/v2/cms/objects/GX9UQZZ12?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
www.crunchyroll.com/content/v2/cms/objects/GEVUZNPQM?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
www.crunchyroll.com/content/v2/cms/objects/G8WUN09V9?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
www.crunchyroll.com/content/v2/cms/objects/G0DUNJ571?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
www.crunchyroll.com/content/v2/cms/objects/GD9UV8M20?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
www.crunchyroll.com/content/v2/cms/objects/GQJUGQD5Q?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
www.crunchyroll.com/content/v2/cms/objects/GVWU048XM?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
www.crunchyroll.com/content/v2/cms/objects/G8WUN0W03?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
www.crunchyroll.com/content/v2/cms/objects/G7PU4JMEM?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
www.crunchyroll.com/content/v2/cms/objects/GZ7UV1KQE?locale=en-GB:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()`

**Comment by ElgarL** [comment]
The right hand pane has an error too `Uncaught (in promise) Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error:  (-3) loading 'https://www.crunchyroll.com/'
    at t.ipcRendererInternal.invoke (node:electron/js2c/renderer_init:2:11128)`

**Comment by Tenpi** [comment]
Did Crunchyroll remove English (UK)? I originally thought it didn't appear because I'm from the US. 

<img width="196" alt="Screenshot 2024-02-10 at 10 24 27 PM" src="https://github.com/Tenpi/Crunchyroll-Downloader/assets/37512637/4bc5dad6-b420-429c-82dd-fe75b4d0f3fd">

**Comment by ElgarL** [comment]
Seems so, no more UK only US. I changed my settings to US and it now downloads.

**Comment by Tenpi** [comment]
Probably fixed in `v0.6.9`
