### ISSUE TITLE
Update does nothing

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#81]
The auto update under Win7 seems to do nothing. It detects a new version, but when clicking yes, nothing happens.

`node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error invoking remote method 'install-update': Error: Cannot download "https://github.com/Tenpi/Crunchyroll-Downloader/releases/download/v0.7.0/Crunchyroll-Downloader-Setup-0.7.0.exe", status 404: 
    at a.invoke (node:electron/js2c/renderer_init:2:7610)`

It now installs fine so long as you Use the Registry hack and right click to install without Privilege elevation.

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\forcerunasinvoker]
@="Run without privilege elevation"

[HKEY_CLASSES_ROOT\*\shell\forcerunasinvoker\command]
@="cmd /min /C \"set __COMPAT_LAYER=RUNASINVOKER && start \"\" \"%1\"\""

**Comment by Tenpi** [comment]
Fixed
