### ISSUE TITLE
Search/download broke in 0.6.8+

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#82]
Search using "in another world with my smartphone"
https://www.crunchyroll.com/content/v2/discover/search?q=in%20another%20world%20with%20my%20smartphone

Failed to load resource: the server responded with a status of 401 ()

Entering the full address
https://www.crunchyroll.com/series/GYQ4ZWV46/in-another-world-with-my-smartphone

Failed to load resource: the server responded with a status of 401 ()
VM185:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON

**Comment by Tenpi** [comment]
401 error means you have to login because it requires an authorization token. Anything that works without logging in is a fluke tbh. I fixed a different bug not mentioned here in `v0.7.1`.

**Comment by ElgarL** [comment]
In that case the login is broken in 0.7.1 internal browser. I can log in fine in a normal browser.

Error when trying to log in  with internal browser (email or password is incorrect). Tested on Win 7 and 11

Uncaught (in promise) Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error:  (-3) loading 'https://www.crunchyroll.com/'
    at t.ipcRendererInternal.invoke (node:electron/js2c/renderer_init:2:11754)

**Comment by ElgarL** [comment]
Never mind. It was my error. I hit the failed login attempts.
