### ISSUE TITLE
Burnt in Subs are MASSIVE!

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#87]
I'm not sure why its burning in subs and adding a sub track (VP8).

Crunchyroll playing with subs...
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/4a3d6949-8818-4fb2-a917-7134f8db9691)

WEBM from this with sub track...
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/e3652826-b8a7-4d5f-9ca1-ce4556c94dce)
The LARGE black outlined subs are burnt in.

**Comment by Tenpi** [comment]
There is a setting to change the font size. Are you downloading in 1080/720p resolution? Anything lower and the font size will look pretty big. 

As for outline I can add an option to change the thickness if you don't like it. 

Sadly there doesn't seem to be consistency with how ffmpeg burns the subtitles and how a video player plays the subtitle file separately, so you have to change the settings depending on whether you want hard sub or soft sub.

**Comment by ElgarL** [comment]
Is there a way to have no burnt in subs at all?

**Comment by Tenpi** [comment]
It should be fixed in 0.7.7
