### ISSUE TITLE
Low bitrate using VP8.

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#90]
Using the same config settings of 10 quality the bit rate for VP8 is so low it artifacts. Changing the quality will make no difference, see my other ticket  #92

H265/MP4
> Format                                   : MPEG-4
> Format profile                           : Base Media
> Codec ID                                 : isom (isom/iso2/mp41)
> File size                                : 564 MiB
> Duration                                 : 24 min 37 s
> Overall bit rate                         : 3 201 kb/s
> Frame rate                               : 29.970 FPS
> Writing application                      : Lavf59.30.100

VP8/WEBM
> Format                                   : WebM
> Format version                           : Version 2
> File size                                : 61.3 MiB
> Duration                                 : 24 min 37 s
> Overall bit rate mode                    : Variable
> Overall bit rate                         : 348 kb/s
> Frame rate                               : 29.970 FPS
> Writing application                      : Lavf59.30.100
> Writing library                          : Lavf59.30.100

VP9/WEBM
> Format                                   : WebM
> Format version                           : Version 4
> File size                                : 583 MiB
> Duration                                 : 24 min 37 s
> Overall bit rate                         : 3 311 kb/s
> Frame rate                               : 29.970 FPS
> Writing application                      : Lavf59.30.100
> Writing library                          : Lavf59.30.100

**Comment by ElgarL** [comment]
Yes however setting 0 will throw an error when set to VP8.

**Comment by Tenpi** [comment]
The bitrate should be higher but if it's not enough for you, append it to the command with `-b:v <bitrate>`

**Comment by ElgarL** [comment]
Its literally 200 to 300 instead of 3k like H265 and VP9
