### ISSUE TITLE
Min/Max quality levels.

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#91]
For VP8 WEBM it's 4-63, but the setting makes no difference. See #92 
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/62ab148b-3b5d-4073-9816-8d77cdf91591)

**Comment by Tenpi** [comment]
I increased the maximum allowed value to 63

**Comment by ElgarL** [comment]
Why does it error with zero?
