### ISSUE TITLE
Quality setting has no effect for VP8 WEBM.

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#92]
Setting quality of 4 in config for VP8
> Video
> ID                                       : 1
> Format                                   : VP8
> Codec ID                                 : V_VP8
> Duration                                 : 24 min 37 s
> Bit rate                                 : 213 kb/s
> Width                                    : 640 pixels
> Height                                   : 480 pixels
> Display aspect ratio                     : 4:3
> Frame rate mode                          : Constant
> Frame rate                               : 29.970 (30000/1001) FPS
> Compression mode                         : Lossy
> Bits/(Pixel*Frame)                       : 0.023
> Stream size                              : 37.6 MiB (61%)
> Writing library                          : Lavc59.42.102 libvpx
> Default                                  : No
> Forced                                   : No
> VARIANT_BITRATE                          : 0

Setting of 51 (can't set to 64 as capped)
> Video
> ID                                       : 1
> Format                                   : VP8
> Codec ID                                 : V_VP8
> Duration                                 : 24 min 37 s
> Bit rate                                 : 212 kb/s
> Width                                    : 640 pixels
> Height                                   : 480 pixels
> Display aspect ratio                     : 4:3
> Frame rate mode                          : Constant
> Frame rate                               : 29.970 (30000/1001) FPS
> Compression mode                         : Lossy
> Bits/(Pixel*Frame)                       : 0.023
> Stream size                              : 37.4 MiB (61%)
> Writing library                          : Lavc59.42.102 libvpx
> Default                                  : No
> Forced                                   : No
> VARIANT_BITRATE                          : 0

**Comment by ElgarL** [comment]
The string I used in my GUI WEBM converter I wrote years ago...
```ffmpeg.exe -y -threads 0 -i %1 -map 0:0 -map 0:1 -codec:v libvpx -codec:a vorbis -b:a 22050 -ac 2 -quality good -cpu-used 0 -b:v 1600k -maxrate 1600k -bufsize 3200k -q:v 0 -strict experimental %2.webm```

**Comment by Tenpi** [comment]
I will just let you append your own arguments to the ffmpeg command since it seems like you want to set higher bitrates than the default.

**Comment by ElgarL** [comment]
This ticket is not so much about setting my own bitrate, it's about the quality setting having no effect and resulting in 200kbs no matter what its set to.

**Comment by Tenpi** [comment]
The quality setting doesn't affect bitrate it affects compression efficiency (0 is lossless, 51 is extremely compressed/low quality). See here: https://trac.ffmpeg.org/wiki/Encode/H.264#crf

**Comment by ElgarL** [comment]
Yes, however it makes no difference in the current build. First you can't set 0 as it errors as when encoding VP8 it only accepts 4-63 and no matter what you set it to the file is the same size and quality when encoding VP8.

**Comment by Tenpi** [comment]
In 0.7.8 set the bitrate that you want by appending `-b:v <bitrate>`.
