### ISSUE TITLE
Quality setting of Zero errors when encoding VP8 and ONLY on VP8

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#93]
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/04b25ad8-284b-4108-9e8f-070b90cb654b)

**Comment by Tenpi** [comment]
Don't open a duplicate issue please just comment if you want more clarification. #91 

VP8 only accepts the range 4-63 don't ask me why because that's how the codec developers set it.

**Comment by ElgarL** [comment]
I'm only trying to help here with decades of programming experience, but closing tickets before they are properly resolved gets no where.

If you want to prevent users seeing errors when they select VP8 with a compression of 0 you can add args ```-qmin 0 -qmax 50```
This will also constrain the upper bounds of compression which will also result in a higher bitrate. As Anime is generally quite simple in it's frame composition (when using VP8) it can easily undershoot the maximum bitrate and complex frames end up falling back to a simple variable bitrate. The end result is a video with artifacts, low bitrate and a VERY small size.
These args should only be added for VP8 so are not appropriate for adding the manual args in the config.

**Comment by Tenpi** [comment]
the qmin option is in 0.8.0
