### ISSUE TITLE
Layout bug in settings

### ISSUE THREAD

**Issue by Pipixel** [Tenpi/Crunchyroll-Downloader#94]
![Crunchyroll_Downloader_82JDKjawc6](https://github.com/Tenpi/Crunchyroll-Downloader/assets/66361896/23ef5837-4196-46a2-baa0-269832c682f2)

**Comment by San3-Cod3** [comment]
My issue #89  was marked as solved in version: 0.7.8: But shall I wait for a 0.7.9+ then? as I haven't tested it yet.  And this current issue to me looks like its related to my issue potentially.

**Comment by Tenpi** [comment]
Was fixed in 0.7.9

**Comment by San3-Cod3** [comment]
@Pipixel - just curious which *.gif software/applications you used and/or use?

Thanks.
