### ISSUE TITLE
Feature request: Subtitles/Subs separate external file (ASS/VTT) download for the English DUB I.E being any Closed Captions available and/or Translation Sign Subtitles available for the DUB

### ISSUE THREAD

**Issue by San3-Cod3** [Tenpi/Crunchyroll-Downloader#96]
Feature request: Subtitles/Subs separate external file (ASS/VTT) download for the English DUB I.E being any Closed Captions available and/or Translation Sign Subtitles available for the DUB.

It would be nice to be able to separately download the Subtitles for the English DUB, like you can with the original JPN Audio when downloading a Subbed episode.  An external file mind you, and not muxed into video, not like an *.mkv attachment; separate downloadable external Subtitle file whether it be ass or vtt, for the English DUB.

Reason for this is two-fold: 1) Because certain anime are heavily signed with Japanese, and when watching Subbed, this is fine as the Signs are translated along with the rest of the episode, but when watching the DUB without the added external subtitle file (ass/vtt/srt) - whether that be a Closed Captions ass/vtt or just TS ass/vtt, none of the signage is translated for you without it; and yes, you can still watch, enjoy and understand the episode, but some meaning is lost when signs can't be read or understood. And 2) Is because in certain heavy action scenes with a lot going on, it can be hard to hear and discern certain technique words being spoken in the episode as one example, due to other noises like intense background music and other chaos happening in a busy scene, so Closed Captions would be nice for the DUB if available on the site, but just the Translation Sign Subtitle files are fine too if that's all they have -- I know Funimation was more big on Closed Captions for DUBS, and CR not so much; mainly TS, but should get better with the merger EVENTUALLY.

I have manipulated the GUI somewhat to show an example of what would be a nice option to have, below:

### **Type:** dub __|__ Language: English __|__ Format: ass/vtt/srt __|__ Quality: 1080p
![ss (2024-02-19 at 03 23 55)](https://github.com/Tenpi/Crunchyroll-Downloader/assets/95466780/2e74ac65-148e-4b4d-94a0-d2913297c31a)

![ss (2024-02-19 at 03 25 28)](https://github.com/Tenpi/Crunchyroll-Downloader/assets/95466780/fa3b80fa-d408-4a16-a739-6013011a3755)

The downloaded example subtitle file is from the SUB (JPN Audio), and not from the English DUB as the option isn't there for it in the GUI, as far as I can tell.  So, if the feature was added, it would show the usual 'pink and white ass symbol', but would say something like: 'English sub for English dub'; or something to that effect right above the progress bar.

I manipulated the GUI's checkbox mode and switched it back, just to show you what I would like as an example for separate external subtitle option when downloading the DUB.  As 'Format:' 'ass'+'vtt' can't be selected or chosen when 'Type:' is 'dub', but they can be when 'Type:' is 'sub'.

Obviously, back in the ol' days, often subtitled anime had hardsubs also known as burned in, so TL Signs were often burned in to video image, but not an option with soft subs.

I hope I have made this request clear and thank you for your great contributions!

And I apologise in advance if the option is already there and I just missed it somehow...

**Comment by ElgarL** [comment]
I'd vote for this. As Subs are sometimes different between English and Japanese. The new VTT option for Sub is nice, but OP is correct in it not being available for Dub.

**Comment by Tenpi** [comment]
Hidive and Funimation have this, I never noticed dub captions on Crunchyroll even if the show has "English CC" most of the time it's empty lol. But thanks for mentioning Code Geass that looks like one of the few shows that has them.

**Comment by San3-Cod3** [comment]
@Tenpi - Would you be okay with adding this feature for the CR portion of the application?

So that all three (CR, FU, HI) content provider parts of the software have the English DUB Subtitles available for separate download?

No rush or anything, just not sure if the feature has been approved for implementation yet? Or whether it'll be labelled as won't add.

**Comment by Tenpi** [comment]
calm down. If I didn't mark it as "won't add" it will probably be added when I have time. -> `v0.8.1`
