### ISSUE TITLE
Feature Request; not important or pressing, no rush: Banner / KeyArt Image Download

### ISSUE THREAD

**Issue by San3-Cod3** [Tenpi/Crunchyroll-Downloader#98]
It would be cool to grab the full size Banner or KeyArt imagery from whichever anime page you're on, using the GUI and a few button presses.

By selecting something like, "Type: dub/sub" and "Format:" 'png banner' / 'png keyart'

Example Banner:
![ss (2024-03-03 at 09 55 32)](https://github.com/Tenpi/Crunchyroll-Downloader/assets/95466780/db4f71f6-5935-4c1c-83e9-5a706955e61c)

The Banner would be this image, at the top of page (centre):
![ss (2024-03-03 at 09 50 36)](https://github.com/Tenpi/Crunchyroll-Downloader/assets/95466780/23ea13eb-891f-48e0-ab76-76b5f8e486f4)

GUI mockup example of requested feature:
![transformed_thumbnail - 15](https://github.com/Tenpi/Crunchyroll-Downloader/assets/95466780/3edb2c22-768a-4f3f-bbfd-5e2a3524064c)

**Comment by Tenpi** [comment]
do you want the box art also?

**Comment by San3-Cod3** [comment]
Sure, if that isn't too much trouble.

My favourite style of art was when they used to look like image#2 (640x960 Dimensions), but sadly I don't see this version around anymore; although sometimes you can get lucky in Google if a website has a promo image like that.

`art`

![Tower of God bannerart1](https://github.com/Tenpi/Crunchyroll-Downloader/assets/95466780/301bca41-8ef2-49cd-873f-bb82c0148546)
![Tower of God keyart1](https://github.com/Tenpi/Crunchyroll-Downloader/assets/95466780/22295339-2bb5-451a-813f-0434140519db)
![Tower of God keyart2](https://github.com/Tenpi/Crunchyroll-Downloader/assets/95466780/b0679c11-f32a-4741-8641-78ccf5ce47bc)

**Comment by Tenpi** [comment]
Added in 0.8.2
