### ISSUE TITLE
Cannot paste link or searching for anime

### ISSUE THREAD

**Issue by MLB-11** [Tenpi/Crunchyroll-Downloader#99]
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/98657556/681ffaef-a82a-4fa4-a155-c1f2ce75bfb7)
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/98657556/238f4e6f-b574-4bf2-86b0-00762fb1e29e)

**Comment by ElgarL** [comment]
It looks like you are not logged in on the internal browser.

**Comment by MLB-11** [comment]
ah thanks, my bad I just saw the login button
